export const Images = {
  welcomeImage: require('../assets/image/wlcbackgroundimg.png'),
  google: require('../assets/image/google.png'),
  apple: require('../assets/image/apple.png'),
}

export const Strings = {
  WELCOME_TEXT: 'Welcome to GYMRATS AI',
  WELCOME_DESCRIPTION_TEXT: `Reimagine\nYour Workout\nand Meal Plan\nwith A.I`,
  SIGN_UP: 'Sign Up',
  LETS_GO: 'Let’s Go',
  LOGIN: 'Login',
  OR: 'Or',
  GOOGLE_BUTTON_TEXT: 'Continue with Google',
  APPLE_BUTTON_TEXT: 'Continue with Apple',
  SET_UP_PROFILE: 'Set up your profile',
  PROFILE_DESCRIPTION: `Create an account to get your workout plans\nand meal plans`,
  FRIST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONTINUE: 'Continue',
  OTP_DESCRIPTION_TEXT: `Enter the verification code that was sent to\nyour inbox`,
  CONFRIMATION_CODE: 'Confirmation Code',
  ENTER_CODE: 'Enter code',
  CONFRIM: 'Confirm',
  SUCCESSFULLY_VERIFIED: 'Successfully Verified',
  CHECK_IN: 'Check In',
  ADD_GOAL_AND_METRICS: 'Add Goal and metrics',
  ADD_GOAL_SCREEN_DESCRIPTION_TEXT: `Enter the Goal you wanna achieve, height,\nweight and more.`,
  HEIGHT_CMS: 'Height (cms)',
  HEIGHT: 'Height',
  WEIGHT_LBS: 'Weight (lbs)',
  WEIGHT: 'Weight',
  GENDER: 'Gender',
  AGE: 'Age',
  GOAL: 'Goal',
  SIGN_IN_TITLE: 'Login into Gymrat AI',
  SIGN_IN_DESCRIPTION_TEXT: `Enter your login credentials to access your\naccount`,
  UPDATE_GOAL: 'Update Goal',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  EMAIL_ADDRESS: 'Email Address',
  ACCOUNT_LINK: 'Account Linked',
  LOG_OUT: 'Logout',
}
