export const ROUTES = {
  ONBOARDING_STACK: 'OnboardingStack',
  APP_SCREEN: ' App',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  WELCOME_SCREEN: 'WelcomeScreen',
  SIGN_IN_SCREEN: 'SignInScreen',
  CHANGE_PASSWORD: 'ChangePassword',
  ADD_MORE_DETAILS_SCREEN: 'AddMoreDetailsScreen',
  HOME_SCREEN: 'HomeScreen',
  CONFIRM_CHANGE_PASSWORD: 'ConfirmChangePassword',
  SIGN_UP_SCREEN: 'SignUpScreen',
  SIGN_UP_OPTIONS_SCREEN: 'SignUpOptionsScreen',
  SIGN_UP_DETAILS_SCREEN: 'SignUpDetailsScreen',
  SIGN_UP_OTP_SCREEN: 'SignUpOtpScreen',
  SIGN_UP_CONFIRM_SCREEN: 'SignUpConfirmScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  AUTH_STACK: 'AuthStack',
  WORKOUT_DETAILS: 'Workoutscreen',
  MEAL_DETAILS: 'MealScreen',
  HOME_STACK: 'HomeStack',
}
